include("array-loops-advanced.jl")
include("array-loops.jl")
include("pre-allocation.jl")
include("untyped-variables.jl")
include("abstract-type.jl")
include("function-barriers.jl")
include("captured-variable.jl")
include("views.jl")